/**
 * Integration tests for format converters
 * Tests real-world scenarios and edge cases
 */

import {
  convertToSRT,
  convertToVTT,
  convertToASS,
  convertToJSON,
  validateForFormat
} from '../format-converters'
import type { SubtitleEntry } from '../../types/subtitle'
import type { ExportSettings } from '../../stores/export-store'

describe('Format Converters Integration Tests', () => {
  describe('Real-world subtitle scenarios', () => {
    const realWorldSubtitles: SubtitleEntry[] = [
      {
        id: 'sub_1',
        index: 0,
        startTime: 0.0,
        endTime: 3.2,
        duration: 3.2,
        text: '大家好，歡迎收看今日新聞',
        translation: 'Hello everyone, welcome to today\'s news',
        confidence: 98.5,
        speaker: '主播'
      },
      {
        id: 'sub_2',
        index: 1,
        startTime: 3.8,
        endTime: 7.1,
        duration: 3.3,
        text: '今日天氣晴朗，氣溫攝氏25度',
        translation: 'Today\'s weather is sunny, temperature is 25 degrees Celsius',
        confidence: 96.2,
        speaker: '氣象員'
      },
      {
        id: 'sub_3',
        index: 2,
        startTime: 8.0,
        endTime: 12.5,
        duration: 4.5,
        text: '疫情最新消息：新增確診個案20宗',
        translation: 'Latest COVID update: 20 new confirmed cases',
        confidence: 94.8,
        speaker: '記者'
      }
    ]

    const allFeaturesSettings: ExportSettings = {
      selectedFormat: 'srt',
      includeCantonese: true,
      includeEnglish: true,
      includeConfidenceScores: true,
      includeTimestampMetadata: true
    }

    it('should handle long news broadcast with dual language', () => {
      const srtResult = convertToSRT(realWorldSubtitles, allFeaturesSettings)
      
      // Check structure
      expect(srtResult).toContain('1\n00:00:00,000 --> 00:00:03,200')
      expect(srtResult).toContain('2\n00:00:03,800 --> 00:00:07,100')
      expect(srtResult).toContain('3\n00:00:08,000 --> 00:00:12,500')
      
      // Check dual language content
      expect(srtResult).toContain('大家好，歡迎收看今日新聞\nHello everyone, welcome to today\'s news')
      expect(srtResult).toContain('今日天氣晴朗，氣溫攝氏25度\nToday\'s weather is sunny, temperature is 25 degrees Celsius')
      
      // Check confidence scores
      expect(srtResult).toContain('[Confidence: 98.5%]')
      expect(srtResult).toContain('[Confidence: 96.2%]')
      expect(srtResult).toContain('[Confidence: 94.8%]')
    })

    it('should generate valid VTT with metadata for news broadcast', () => {
      const vttResult = convertToVTT(realWorldSubtitles, allFeaturesSettings)
      
      expect(vttResult).toStartWith('WEBVTT\n')
      expect(vttResult).toContain('NOTE\nGenerated by CantoCap at')
      expect(vttResult).toContain('Subtitle count: 3')
      expect(vttResult).toContain('Language settings: Cantonese(true), English(true)')
      
      // Check VTT timing format
      expect(vttResult).toContain('00:00:00.000 --> 00:00:03.200 line:90%')
      expect(vttResult).toContain('00:00:03.800 --> 00:00:07.100 line:90%')
    })

    it('should create proper ASS styles for news broadcast', () => {
      const assResult = convertToASS(realWorldSubtitles, allFeaturesSettings)
      
      expect(assResult).toContain('[Script Info]')
      expect(assResult).toContain('Title: CantoCap Generated Subtitles')
      
      // Check dual language styles
      expect(assResult).toContain('Style: Cantonese,')
      expect(assResult).toContain('Style: English,')
      
      // Check events
      expect(assResult).toContain('Dialogue: 0,0:00:00.00,0:00:03.20,Cantonese,,0,0,0,,大家好，歡迎收看今日新聞')
      expect(assResult).toContain('Dialogue: 0,0:00:00.00,0:00:03.20,English,,0,0,0,,Hello everyone, welcome to today\'s news')
    })

    it('should export comprehensive JSON with all metadata', () => {
      const jsonResult = convertToJSON(realWorldSubtitles, allFeaturesSettings)
      const parsed = JSON.parse(jsonResult)
      
      // Check metadata
      expect(parsed.metadata.format).toBe('CantoCap JSON Subtitle Export')
      expect(parsed.metadata.statistics.totalSubtitles).toBe(3)
      expect(parsed.metadata.statistics.totalDuration).toBe(12.5)
      expect(parsed.metadata.statistics.averageConfidence).toBeCloseTo(96.5, 1)
      
      // Check subtitle data
      expect(parsed.subtitles[0]).toEqual({
        index: 0,
        startTime: 0.0,
        endTime: 3.2,
        duration: 3.2,
        cantonese: '大家好，歡迎收看今日新聞',
        english: 'Hello everyone, welcome to today\'s news',
        confidence: 98.5,
        timestamps: {
          start: '00:00:00,000',
          end: '00:00:03,200',
          duration: '3.200s'
        }
      })
    })
  })

  describe('Edge case handling', () => {
    const edgeCaseSubtitles: SubtitleEntry[] = [
      {
        id: 'edge_1',
        index: 0,
        startTime: 0.001,
        endTime: 0.099,
        duration: 0.098,
        text: '快',
        confidence: 50.0
      },
      {
        id: 'edge_2',
        index: 1,
        startTime: 3599.5,
        endTime: 3661.25,
        duration: 61.75,
        text: 'Very long subtitle that spans over a minute and contains special characters: <>"\',;!@#$%^&*()[]{}|\\',
        translation: 'A very long English translation that also spans a very long time and contains special characters',
        confidence: 99.9
      },
      {
        id: 'edge_3',
        index: 2,
        startTime: 7200.0,
        endTime: 7200.5,
        duration: 0.5,
        text: '',
        translation: '',
        confidence: 0
      }
    ]

    const basicSettings: ExportSettings = {
      selectedFormat: 'srt',
      includeCantonese: true,
      includeEnglish: false,
      includeConfidenceScores: false,
      includeTimestampMetadata: false
    }

    it('should handle very short duration subtitles', () => {
      const result = convertToSRT(edgeCaseSubtitles.slice(0, 1), basicSettings)
      expect(result).toContain('00:00:00,001 --> 00:00:00,099')
      expect(result).toContain('快')
    })

    it('should handle hour+ timestamps correctly', () => {
      const result = convertToSRT(edgeCaseSubtitles.slice(1, 2), basicSettings)
      expect(result).toContain('00:59:59,500 --> 01:01:01,250')
    })

    it('should handle 2+ hour timestamps', () => {
      const result = convertToSRT(edgeCaseSubtitles.slice(2, 3), basicSettings)
      expect(result).toContain('02:00:00,000 --> 02:00:00,500')
    })

    it('should handle special characters in all formats', () => {
      const specialCharSubtitle = edgeCaseSubtitles.slice(1, 2)
      
      const srtResult = convertToSRT(specialCharSubtitle, basicSettings)
      const vttResult = convertToVTT(specialCharSubtitle, basicSettings)
      const assResult = convertToASS(specialCharSubtitle, basicSettings)
      const jsonResult = convertToJSON(specialCharSubtitle, basicSettings)
      
      // All should contain the special characters
      const specialText = 'special characters: <>"\',;!@#$%^&*()[]{}|\\'
      
      expect(srtResult).toContain(specialText)
      expect(vttResult).toContain(specialText)
      expect(assResult).toContain(specialText)
      expect(jsonResult).toContain(specialText)
    })

    it('should handle empty text gracefully', () => {
      const emptySubtitle = edgeCaseSubtitles.slice(2, 3)
      
      const srtResult = convertToSRT(emptySubtitle, basicSettings)
      const jsonResult = convertToJSON(emptySubtitle, basicSettings)
      
      expect(srtResult).toContain('3\n02:00:00,000 --> 02:00:00,500\n\n')
      
      const parsed = JSON.parse(jsonResult)
      expect(parsed.subtitles[0].cantonese).toBe('')
    })
  })

  describe('Validation integration', () => {
    it('should detect all issues in problematic subtitle set', () => {
      const problematicSubtitles: SubtitleEntry[] = [
        {
          id: 'prob_1',
          index: 0,
          startTime: 0.5,
          endTime: 0.7, // Too short
          duration: 0.2,
          text: 'Contains --> arrow which breaks VTT'
        },
        {
          id: 'prob_2',
          index: 1,
          startTime: 0.6, // Overlaps with previous
          endTime: 2.0,
          duration: 1.4,
          text: 'A'.repeat(300) // Too long for ASS
        },
        {
          id: 'prob_3',
          index: 2,
          startTime: 1.8, // Overlaps with previous
          endTime: 2.1,
          duration: 0.3, // Too short
          text: 'Another --> problem'
        }
      ]

      const srtIssues = validateForFormat(problematicSubtitles, 'srt')
      const vttIssues = validateForFormat(problematicSubtitles, 'vtt')
      const assIssues = validateForFormat(problematicSubtitles, 'ass')

      // Common issues
      expect(srtIssues).toContain('Timing overlap detected between subtitle 1 and 2')
      expect(srtIssues).toContain('Timing overlap detected between subtitle 2 and 3')
      expect(srtIssues).toContain('2 subtitles have very short duration (<0.5s)')

      // VTT specific
      expect(vttIssues).toContain('2 subtitles contain invalid characters for VTT format')

      // ASS specific
      expect(assIssues).toContain('1 subtitles may be too long for ASS format')
    })

    it('should pass validation for well-formed subtitles', () => {
      const goodSubtitles: SubtitleEntry[] = [
        {
          id: 'good_1',
          index: 0,
          startTime: 0.5,
          endTime: 2.5,
          duration: 2.0,
          text: 'Well formatted subtitle'
        },
        {
          id: 'good_2',
          index: 1,
          startTime: 3.0,
          endTime: 5.5,
          duration: 2.5,
          text: 'Another good subtitle'
        }
      ]

      const srtIssues = validateForFormat(goodSubtitles, 'srt')
      const vttIssues = validateForFormat(goodSubtitles, 'vtt')
      const assIssues = validateForFormat(goodSubtitles, 'ass')
      const jsonIssues = validateForFormat(goodSubtitles, 'json')

      expect(srtIssues).toEqual([])
      expect(vttIssues).toEqual([])
      expect(assIssues).toEqual([])
      expect(jsonIssues).toEqual([])
    })
  })

  describe('Cross-format consistency', () => {
    const testSubtitles: SubtitleEntry[] = [
      {
        id: 'test_1',
        index: 0,
        startTime: 1.5,
        endTime: 4.2,
        duration: 2.7,
        text: '測試字幕',
        translation: 'Test subtitle',
        confidence: 87.3
      }
    ]

    const settingsWithAll: ExportSettings = {
      selectedFormat: 'srt',
      includeCantonese: true,
      includeEnglish: true,
      includeConfidenceScores: true,
      includeTimestampMetadata: true
    }

    it('should maintain timing consistency across formats', () => {
      const srtResult = convertToSRT(testSubtitles, settingsWithAll)
      const vttResult = convertToVTT(testSubtitles, settingsWithAll)
      const assResult = convertToASS(testSubtitles, settingsWithAll)
      const jsonResult = convertToJSON(testSubtitles, settingsWithAll)

      // SRT timing
      expect(srtResult).toContain('00:00:01,500 --> 00:00:04,200')
      
      // VTT timing  
      expect(vttResult).toContain('00:00:01.500 --> 00:00:04.200')
      
      // ASS timing
      expect(assResult).toContain('0:00:01.50,0:00:04.20')
      
      // JSON timing
      const parsed = JSON.parse(jsonResult)
      expect(parsed.subtitles[0].startTime).toBe(1.5)
      expect(parsed.subtitles[0].endTime).toBe(4.2)
      expect(parsed.subtitles[0].timestamps.start).toBe('00:00:01,500')
      expect(parsed.subtitles[0].timestamps.end).toBe('00:00:04,200')
    })

    it('should maintain content consistency across formats', () => {
      const srtResult = convertToSRT(testSubtitles, settingsWithAll)
      const vttResult = convertToVTT(testSubtitles, settingsWithAll)
      const jsonResult = convertToJSON(testSubtitles, settingsWithAll)

      // All should contain the same text content
      expect(srtResult).toContain('測試字幕\nTest subtitle\n[Confidence: 87.3%]')
      expect(vttResult).toContain('測試字幕\nTest subtitle\n[Confidence: 87.3%]')
      
      const parsed = JSON.parse(jsonResult)
      expect(parsed.subtitles[0].cantonese).toBe('測試字幕')
      expect(parsed.subtitles[0].english).toBe('Test subtitle')
      expect(parsed.subtitles[0].confidence).toBe(87.3)
    })

    it('should respect setting changes consistently', () => {
      const cantoneseOnlySettings: ExportSettings = {
        ...settingsWithAll,
        includeEnglish: false,
        includeConfidenceScores: false
      }

      const srtResult = convertToSRT(testSubtitles, cantoneseOnlySettings)
      const vttResult = convertToVTT(testSubtitles, cantoneseOnlySettings)
      const jsonResult = convertToJSON(testSubtitles, cantoneseOnlySettings)

      // Should only contain Cantonese text
      expect(srtResult).toContain('測試字幕')
      expect(srtResult).not.toContain('Test subtitle')
      expect(srtResult).not.toContain('Confidence')

      expect(vttResult).toContain('測試字幕')
      expect(vttResult).not.toContain('Test subtitle')
      expect(vttResult).not.toContain('Confidence')

      const parsed = JSON.parse(jsonResult)
      expect(parsed.subtitles[0].cantonese).toBe('測試字幕')
      expect(parsed.subtitles[0].english).toBeUndefined()
      expect(parsed.subtitles[0].confidence).toBeUndefined()
    })
  })
})