import { convertToSRT, convertToVTT, convertToASS, convertToJSON, validateForFormat } from '../format-converters'
import type { SubtitleEntry } from '../../types/subtitle'
import type { ExportSettings } from '../../stores/export-store'

// Mock subtitle data for testing
const mockSubtitles: SubtitleEntry[] = [
  {
    id: '1',
    index: 1,
    startTime: 2.5,
    endTime: 6.0,
    duration: 3.5,
    text: '你好，歡迎收看今日嘅新聞',
    originalText: '你好，歡迎收看今日嘅新聞',
    confidence: 95,
    translation: 'Hello, welcome to today\'s news'
  },
  {
    id: '2',
    index: 2,
    startTime: 8.0,
    endTime: 12.5,
    duration: 4.5,
    text: '今日天氣非常之好',
    originalText: '今日天氣非常之好',
    confidence: 88,
    translation: 'The weather is very good today'
  }
]

const defaultSettings: ExportSettings = {
  selectedFormat: 'srt',
  includeCantonese: true,
  includeEnglish: true,
  includeConfidenceScores: false,
  includeTimestampMetadata: false
}

describe('Format Converters', () => {
  describe('convertToSRT', () => {
    it('should convert subtitles to SRT format with dual language', () => {
      const result = convertToSRT(mockSubtitles, defaultSettings)
      
      expect(result).toContain('1\n00:00:02,500 --> 00:00:06,000')
      expect(result).toContain('你好，歡迎收看今日嘅新聞')
      expect(result).toContain('Hello, welcome to today\'s news')
      expect(result).toContain('2\n00:00:08,000 --> 00:00:12,500')
    })

    it('should handle Cantonese only', () => {
      const settings = { ...defaultSettings, includeEnglish: false }
      const result = convertToSRT(mockSubtitles, settings)
      
      expect(result).toContain('你好，歡迎收看今日嘅新聞')
      expect(result).not.toContain('Hello, welcome to today\'s news')
    })

    it('should include confidence scores when enabled', () => {
      const settings = { ...defaultSettings, includeConfidenceScores: true }
      const result = convertToSRT(mockSubtitles, settings)
      
      expect(result).toContain('[Confidence: 95%]')
      expect(result).toContain('[Confidence: 88%]')
    })

    it('should handle empty subtitles', () => {
      const result = convertToSRT([], defaultSettings)
      expect(result).toBe('')
    })
  })

  describe('convertToVTT', () => {
    it('should convert subtitles to VTT format with header', () => {
      const result = convertToVTT(mockSubtitles, defaultSettings)
      
      expect(result).toStartWith('WEBVTT\n\n')
      expect(result).toContain('00:00:02.500 --> 00:00:06.000')
      expect(result).toContain('你好，歡迎收看今日嘅新聞')
    })

    it('should include metadata when enabled', () => {
      const settings = { ...defaultSettings, includeTimestampMetadata: true }
      const result = convertToVTT(mockSubtitles, settings)
      
      expect(result).toContain('Generated by CantoCap')
      expect(result).toContain('Subtitle count: 2')
    })

    it('should handle empty subtitles with header', () => {
      const result = convertToVTT([], defaultSettings)
      expect(result).toBe('WEBVTT\n\n')
    })
  })

  describe('convertToASS', () => {
    it('should convert subtitles to ASS format with script info', () => {
      const result = convertToASS(mockSubtitles, defaultSettings)
      
      expect(result).toContain('[Script Info]')
      expect(result).toContain('[V4+ Styles]')
      expect(result).toContain('[Events]')
      expect(result).toContain('Dialogue: 0,0:00:02.50,0:00:06.00')
    })

    it('should create dual language styles when both languages enabled', () => {
      const result = convertToASS(mockSubtitles, defaultSettings)
      
      expect(result).toContain('Style: Cantonese')
      expect(result).toContain('Style: English')
    })

    it('should use default style for single language', () => {
      const settings = { ...defaultSettings, includeEnglish: false }
      const result = convertToASS(mockSubtitles, settings)
      
      expect(result).toContain('Style: Default')
      expect(result).not.toContain('Style: English')
    })
  })

  describe('convertToJSON', () => {
    it('should convert subtitles to JSON format with metadata', () => {
      const result = convertToJSON(mockSubtitles, defaultSettings)
      const parsed = JSON.parse(result)
      
      expect(parsed.metadata).toBeDefined()
      expect(parsed.metadata.format).toBe('CantoCap JSON Subtitle Export')
      expect(parsed.subtitles).toHaveLength(2)
      expect(parsed.subtitles[0].cantonese).toBe('你好，歡迎收看今日嘅新聞')
      expect(parsed.subtitles[0].english).toBe('Hello, welcome to today\'s news')
    })

    it('should include statistics in metadata', () => {
      const result = convertToJSON(mockSubtitles, defaultSettings)
      const parsed = JSON.parse(result)
      
      expect(parsed.metadata.statistics.totalSubtitles).toBe(2)
      expect(parsed.metadata.statistics.averageConfidence).toBe(91.5)
    })

    it('should conditionally include fields based on settings', () => {
      const settings = { 
        ...defaultSettings, 
        includeConfidenceScores: true,
        includeTimestampMetadata: true 
      }
      const result = convertToJSON(mockSubtitles, settings)
      const parsed = JSON.parse(result)
      
      expect(parsed.subtitles[0].confidence).toBe(95)
      expect(parsed.subtitles[0].timestamps).toBeDefined()
      expect(parsed.subtitles[0].timestamps.start).toBe('00:00:02,500')
    })
  })

  describe('validateForFormat', () => {
    it('should return no issues for valid subtitles', () => {
      const issues = validateForFormat(mockSubtitles, 'srt')
      expect(issues).toHaveLength(0)
    })

    it('should detect empty subtitle list', () => {
      const issues = validateForFormat([], 'srt')
      expect(issues).toContain('No subtitles to export')
    })

    it('should detect timing overlaps', () => {
      const overlappingSubtitles = [
        { ...mockSubtitles[0], endTime: 10 },
        { ...mockSubtitles[1], startTime: 8 }
      ]
      const issues = validateForFormat(overlappingSubtitles, 'srt')
      expect(issues.some(issue => issue.includes('Timing overlap'))).toBe(true)
    })

    it('should detect short durations', () => {
      const shortSubtitles = [
        { ...mockSubtitles[0], duration: 0.3 }
      ]
      const issues = validateForFormat(shortSubtitles, 'srt')
      expect(issues.some(issue => issue.includes('very short duration'))).toBe(true)
    })

    it('should detect format-specific issues for VTT', () => {
      const invalidVTTSubtitles = [
        { ...mockSubtitles[0], text: 'Text with --> invalid chars' }
      ]
      const issues = validateForFormat(invalidVTTSubtitles, 'vtt')
      expect(issues.some(issue => issue.includes('invalid characters for VTT'))).toBe(true)
    })
  })

  describe('Time formatting', () => {
    it('should format seconds correctly for SRT', () => {
      // Test through SRT conversion to verify time formatting
      const testSubtitle = [{
        ...mockSubtitles[0],
        startTime: 3661.5, // 1:01:01.500
        endTime: 3665.250   // 1:01:05.250
      }]
      
      const result = convertToSRT(testSubtitle, defaultSettings)
      expect(result).toContain('01:01:01,500 --> 01:01:05,250')
    })

    it('should handle zero padding correctly', () => {
      const testSubtitle = [{
        ...mockSubtitles[0],
        startTime: 5.05,  // 00:00:05.050
        endTime: 9.5      // 00:00:09.500
      }]
      
      const result = convertToSRT(testSubtitle, defaultSettings)
      expect(result).toContain('00:00:05,050 --> 00:00:09,500')
    })
  })
})