import type { SubtitleEntry } from "../types/subtitle";
import type { ExportSettings } from "../stores/export-store";

/**
 * Format time for SRT (SubRip) format
 * Format: HH:MM:SS,mmm
 */
const formatSRTTime = (seconds: number): string => {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const ms = Math.floor((seconds % 1) * 1000);

  return `${hours.toString().padStart(2, "0")}:${minutes
    .toString()
    .padStart(2, "0")}:${secs.toString().padStart(2, "0")},${ms
    .toString()
    .padStart(3, "0")}`;
};

/**
 * Format time for VTT (WebVTT) format
 * Format: HH:MM:SS.mmm
 */
const formatVTTTime = (seconds: number): string => {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const ms = Math.floor((seconds % 1) * 1000);

  return `${hours.toString().padStart(2, "0")}:${minutes
    .toString()
    .padStart(2, "0")}:${secs.toString().padStart(2, "0")}.${ms
    .toString()
    .padStart(3, "0")}`;
};

/**
 * Format time for ASS (Advanced SSA) format
 * Format: H:MM:SS.cc (centiseconds)
 */
const formatASSTime = (seconds: number): string => {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const cs = Math.floor((seconds % 1) * 100); // centiseconds

  return `${hours}:${minutes.toString().padStart(2, "0")}:${secs
    .toString()
    .padStart(2, "0")}.${cs.toString().padStart(2, "0")}`;
};

/**
 * Prepare text content based on export settings
 */
const prepareTextContent = (
  subtitle: SubtitleEntry,
  settings: ExportSettings
): string => {
  const lines: string[] = [];

  // Add Cantonese text if enabled
  if (settings.includeCantonese && subtitle.text) {
    lines.push(subtitle.text);
  }

  // Add English translation if available and enabled
  if (settings.includeEnglish && subtitle.translation) {
    lines.push(subtitle.translation);
  }

  // Add confidence score if enabled
  if (settings.includeConfidenceScores && subtitle.confidence !== undefined) {
    lines.push(`[Confidence: ${subtitle.confidence}%]`);
  }

  return lines.join("\n");
};

/**
 * Convert subtitles to SRT (SubRip) format
 */
export const convertToSRT = (
  subtitles: SubtitleEntry[],
  settings: ExportSettings
): string => {
  if (subtitles.length === 0) return "";

  const srtBlocks = subtitles.map((subtitle, index) => {
    const startTime = formatSRTTime(subtitle.startTime);
    const endTime = formatSRTTime(subtitle.endTime);
    const text = prepareTextContent(subtitle, settings);

    return `${index + 1}\n${startTime} --> ${endTime}\n${text}\n`;
  });

  return srtBlocks.join("\n");
};

/**
 * Convert subtitles to VTT (WebVTT) format
 */
export const convertToVTT = (
  subtitles: SubtitleEntry[],
  settings: ExportSettings
): string => {
  if (subtitles.length === 0) return "WEBVTT\n\n";

  let vttContent = "WEBVTT\n";

  // Add metadata if timestamp metadata is enabled
  if (settings.includeTimestampMetadata) {
    vttContent += `NOTE\nGenerated by CantoCap at ${new Date().toISOString()}\n`;
    vttContent += `Subtitle count: ${subtitles.length}\n`;
    vttContent += `Language settings: Cantonese(${settings.includeCantonese}), English(${settings.includeEnglish})\n\n`;
  } else {
    vttContent += "\n";
  }

  const vttBlocks = subtitles
    .map((subtitle, index) => {
      const startTime = formatVTTTime(subtitle.startTime);
      const endTime = formatVTTTime(subtitle.endTime);
      const text = prepareTextContent(subtitle, settings);

      // Build timestamp line with proper cue settings
      let timestampLine = `${startTime} --> ${endTime}`;

      // Always preserve existing cue settings from original VTT
      if (subtitle.cueSettings) {
        // Use existing cue settings from parsed VTT regardless of content options
        timestampLine += ` ${subtitle.cueSettings}`;
      } else if (
        settings.includeCantonese &&
        settings.includeEnglish &&
        subtitle.translation
      ) {
        // Add default positioning for new dual language content if no existing settings
        timestampLine += ` line:90%`;
      }

      // Only include subtitle if there's content to show
      if (!text.trim()) {
        return null;
      }

      const block = `${index + 1}\n${timestampLine}\n${text}\n`;

      return block;
    })
    .filter(Boolean); // Remove null entries

  return vttContent + vttBlocks.join("\n");
};

/**
 * Convert subtitles to ASS (Advanced SSA) format
 */
export const convertToASS = (
  subtitles: SubtitleEntry[],
  settings: ExportSettings
): string => {
  if (subtitles.length === 0) return "";

  let assContent = "[Script Info]\n";
  assContent += "Title: CantoCap Generated Subtitles\n";
  assContent += "ScriptType: v4.00+\n";
  assContent += "WrapStyle: 0\n";
  assContent += "ScriptType: v4.00+\n";
  assContent += "Collisions: Normal\n";
  assContent += "PlayDepth: 0\n";
  assContent += "Timer: 100.0000\n";
  assContent += "Video Aspect Ratio: 0\n";
  assContent += "Video Zoom: 6\n";
  assContent += "Video Position: 0\n\n";

  // Add styles
  assContent += "[V4+ Styles]\n";
  assContent +=
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n";

  if (settings.includeCantonese && settings.includeEnglish) {
    // Dual language styles
    assContent +=
      "Style: Cantonese,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,40,1\n";
    assContent +=
      "Style: English,Arial,16,&H00FFFF00,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1\n";
  } else {
    // Single language style
    assContent +=
      "Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,25,1\n";
  }

  assContent += "\n[Events]\n";
  assContent +=
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n";

  const assEvents = subtitles.map((subtitle) => {
    const startTime = formatASSTime(subtitle.startTime);
    const endTime = formatASSTime(subtitle.endTime);

    const events: string[] = [];

    // Build subtitle text based on settings
    let subtitleText = "";
    if (settings.includeCantonese && subtitle.text) {
      subtitleText = subtitle.text;
    }
    if (settings.includeEnglish && subtitle.translation) {
      if (subtitleText) {
        subtitleText += "\\N" + subtitle.translation; // \\N is ASS line break
      } else {
        subtitleText = subtitle.translation;
      }
    }

    if (subtitleText) {
      events.push(
        `Dialogue: 0,${startTime},${endTime},Default,,0,0,0,,${subtitleText}`
      );
    }

    return events.join("\n");
  });

  return assContent + assEvents.join("\n") + "\n";
};

/**
 * Convert subtitles to JSON format
 */
export const convertToJSON = (
  subtitles: SubtitleEntry[],
  settings: ExportSettings
): string => {
  const jsonData = {
    metadata: {
      format: "CantoCap JSON Subtitle Export",
      version: "1.0",
      generatedAt: new Date().toISOString(),
      settings: {
        includeCantonese: settings.includeCantonese,
        includeEnglish: settings.includeEnglish,
        includeConfidenceScores: settings.includeConfidenceScores,
        includeTimestampMetadata: settings.includeTimestampMetadata,
      },
      statistics: {
        totalSubtitles: subtitles.length,
        totalDuration:
          subtitles.length > 0 ? subtitles[subtitles.length - 1].endTime : 0,
        averageConfidence:
          subtitles.reduce((sum, sub) => sum + (sub.confidence || 0), 0) /
          subtitles.length,
      },
    },
    subtitles: subtitles.map((subtitle) => {
      const entry: any = {
        index: subtitle.index,
        startTime: subtitle.startTime,
        endTime: subtitle.endTime,
        duration: subtitle.duration,
      };

      // Add text content based on settings
      if (settings.includeCantonese && subtitle.text) {
        entry.caption = subtitle.text;
      }

      if (settings.includeEnglish && subtitle.translation) {
        entry.translation = subtitle.translation;
      }

      // Add optional fields
      if (
        settings.includeConfidenceScores &&
        subtitle.confidence !== undefined
      ) {
        entry.confidence = subtitle.confidence;
      }

      if (settings.includeTimestampMetadata) {
        entry.timestamps = {
          start: formatSRTTime(subtitle.startTime),
          end: formatSRTTime(subtitle.endTime),
          duration: `${subtitle.duration.toFixed(3)}s`,
        };
      }

      // Note: originalText field removed as requested

      return entry;
    }),
  };

  return JSON.stringify(jsonData, null, 2);
};

/**
 * Detect subtitle format from file extension
 */
export const detectFormat = (fileName: string): string => {
  const extension = fileName.toLowerCase().split(".").pop();

  switch (extension) {
    case "srt":
      return "srt";
    case "vtt":
      return "vtt";
    case "ass":
    case "ssa":
      return "ass";
    case "json":
      return "json";
    default:
      return "srt"; // Default to SRT
  }
};

/**
 * Validate subtitle content for format compatibility
 */
export const validateForFormat = (
  subtitles: SubtitleEntry[],
  format: string
): string[] => {
  const issues: string[] = [];

  if (subtitles.length === 0) {
    issues.push("No subtitles to export");
    return issues;
  }

  // Check for timing overlaps
  for (let i = 0; i < subtitles.length - 1; i++) {
    if (subtitles[i].endTime > subtitles[i + 1].startTime) {
      issues.push(
        `Timing overlap detected between subtitle ${i + 1} and ${i + 2}`
      );
    }
  }

  // Check for very short durations
  const shortSubtitles = subtitles.filter((sub) => sub.duration < 0.5);
  if (shortSubtitles.length > 0) {
    issues.push(
      `${shortSubtitles.length} subtitles have very short duration (<0.5s)`
    );
  }

  // Format-specific validations
  switch (format) {
    case "ass":
      // ASS format has specific character limitations
      const longTexts = subtitles.filter(
        (sub) => sub.text && sub.text.length > 200
      );
      if (longTexts.length > 0) {
        issues.push(
          `${longTexts.length} subtitles may be too long for ASS format`
        );
      }
      break;

    case "vtt":
      // VTT format validation
      const invalidChars = subtitles.filter(
        (sub) => sub.text && sub.text.includes("-->")
      );
      if (invalidChars.length > 0) {
        issues.push(
          `${invalidChars.length} subtitles contain invalid characters for VTT format`
        );
      }
      break;
  }

  return issues;
};
